# Liane's Library — Connecting Python to SQL

This notebook demonstrates how to connect a MySQL database to Python using `SQLAlchemy` and `pandas`.
We will:
- Establish a connection to our `sample_library` database
- Read data from SQL into pandas DataFrames
- Insert new data from Python into SQL
- Update existing records

> **Important:** Run this notebook locally (not on Colab). Make sure MySQL is running and your `sample_library` database exists.

---
## 1. Import Libraries

In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

# Check which Python environment we are using
# This should point to your lianes-lib-env
import sys
print(sys.executable)

/opt/anaconda3/envs/lianes-lib-env/bin/python

---
## 2. Connect to the Database

We use a **connection string** to tell Python where to find our MySQL database.
The format is: `mysql+pymysql://user:password@host:port/database_name`

> Only change the `password` variable — everything else stays the same.

In [2]:
# --- Database connection settings ---
schema   = "sample_library"   # name of our database
host     = "127.0.0.1"        # localhost
user     = "root"             # MySQL username
password = os.environ.get("DB_PASSWORD")
port     = 3306               # default MySQL port

# Build the connection string
connection_string = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

print("Connection string created successfully!")

Connection string created successfully!

---
## 3. Read Data from SQL into Python

Using `pd.read_sql()` we can pull data directly from our SQL tables into a pandas DataFrame.
This is the **READ** part of CRUD.

In [3]:
# Read the entire books table
books_df = pd.read_sql("SELECT * FROM books", con=connection_string)
books_df

    title        author      genre          ISBN  is_available
0   Roots  Eric Cantona  biography  000000000001             1
1  Fruits     Roy Keane    cooking  000000000002             1
2    Milk           NaN    cooking  000000000003             1
3  Chairs           NaN  furniture  000000000004             1

In [4]:
# Read the entire friends table
friends_df = pd.read_sql("SELECT * FROM friends", con=connection_string)
friends_df

,friend_id,name_,phone_number,max_loans,notes
0,1,Alice Schmidt,+49123456789,3,Gibt Bücher immer pünktlich zurück
1,2,Bob Müller,+49987654321,2,NaN
2,3,Clara Fischer,+49111222333,2,Vergisst manchmal Rückgabedaten

In [5]:
# Read the entire loans table
loans_df = pd.read_sql("SELECT * FROM loans", con=connection_string)
loans_df

,loan_id,book_id,friend_id,loan_date,return_date,notes
0,1,000000000001,1,2024-01-10,2024-01-25,NaN
1,2,000000000002,2,2024-02-01,2024-03-01,Wartet noch auf Rückgabe
2,3,000000000003,3,2024-02-15,None,NaN

---
## 4. Query: Active Loans

We can also run SQL queries directly from Python.
Here we join all 3 tables to see which books are currently on loan (return_date is NULL).

In [6]:
# Join books, friends and loans to see who has what
active_loans = pd.read_sql("""
    SELECT 
        b.title          AS book_title,
        b.author,
        f.name_          AS borrowed_by,
        f.phone_number   AS contact,
        l.loan_date,
        l.return_date    -- NULL means the book has not been returned yet
    FROM loans l
    JOIN books   b ON l.book_id   = b.ISBN
    JOIN friends f ON l.friend_id = f.friend_id
    WHERE l.return_date IS NULL
""", con=connection_string)

active_loans

  book_title author    borrowed_by       contact   loan_date return_date
0       Milk   None  Clara Fischer  +49111222333  2024-02-15        None

---
## 5. Insert New Data from Python into SQL

We can create a pandas DataFrame in Python and push it directly into our SQL table
using `.to_sql()`. The argument `if_exists='append'` means we add to existing data
without overwriting anything.

This is the **CREATE** part of CRUD.

In [7]:
# Create a new book as a DataFrame
new_book = pd.DataFrame({
    "title":        ["The Alchemist"],
    "author":       ["Paulo Coelho"],
    "genre":        ["fiction"],
    "ISBN":         ["000000000005"],
    "is_available": [1]              # 1 = available
})

# Push the new book into the books table in SQL
new_book.to_sql(
    'books',
    if_exists='append',   # add to existing data, don't overwrite
    con=connection_string,
    index=False           # don't write the pandas index as a column
)

print("New book added successfully!")

New book added successfully!

In [8]:
# Verify the new book is in the database
pd.read_sql("SELECT * FROM books", con=connection_string)

           title        author      genre          ISBN  is_available
0          Roots  Eric Cantona  biography  000000000001             1
1         Fruits     Roy Keane    cooking  000000000002             1
2           Milk           NaN    cooking  000000000003             1
3         Chairs           NaN  furniture  000000000004             1
4  The Alchemist  Paulo Coelho    fiction  000000000005             1

---
## 6. Add a New Friend

Same approach — create a DataFrame and push it to the `friends` table.

In [9]:
# Create a new friend/borrower
new_friend = pd.DataFrame({
    "name_":        ["David Becker"],
    "phone_number": ["+49155123456"],
    "max_loans":    [2],
    "notes":        [None]           # None in Python = NULL in SQL
})

new_friend.to_sql(
    'friends',
    if_exists='append',
    con=connection_string,
    index=False
)

print("New friend added successfully!")

New friend added successfully!

In [10]:
# Verify the new friend is in the database
pd.read_sql("SELECT * FROM friends", con=connection_string)

,friend_id,name_,phone_number,max_loans,notes
0,1,Alice Schmidt,+49123456789,3,Gibt Bücher immer pünktlich zurück
1,2,Bob Müller,+49987654321,2,NaN
2,3,Clara Fischer,+49111222333,2,Vergisst manchmal Rückgabedaten
3,4,David Becker,+49155123456,2,NaN

---
## 7. Update Existing Data

To update data we use `sqlalchemy`'s `engine.connect()` and run a raw SQL UPDATE statement.
The `transaction.commit()` makes the change permanent — without it, the update is lost.

This is the **UPDATE** part of CRUD.

In [11]:
from sqlalchemy import create_engine, text

# Create the engine (needed for UPDATE/DELETE operations)
engine = create_engine(connection_string)

# Mark a book as returned: set return_date for loan_id = 3
update_query = """
    UPDATE loans
    SET return_date = '2024-03-15'
    WHERE loan_id = 3
"""

# Execute with explicit transaction
with engine.connect() as connection:
    transaction = connection.begin()   # start the transaction
    try:
        connection.execute(text(update_query))
        transaction.commit()           # save the changes permanently
        print("Loan updated successfully!")
    except:
        transaction.rollback()         # undo changes if something goes wrong
        raise

Loan updated successfully!

In [12]:
# Also update is_available in books table
update_book_query = """
    UPDATE books
    SET is_available = 1
    WHERE ISBN = '000000000003'
"""

with engine.connect() as connection:
    transaction = connection.begin()
    try:
        connection.execute(text(update_book_query))
        transaction.commit()
        print("Book availability updated!")
    except:
        transaction.rollback()
        raise

Book availability updated!

In [13]:
# Verify the update — no more NULL in return_date for loan 3
pd.read_sql("SELECT * FROM loans", con=connection_string)

,loan_id,book_id,friend_id,loan_date,return_date,notes
0,1,000000000001,1,2024-01-10,2024-01-25,NaN
1,2,000000000002,2,2024-02-01,2024-03-01,Wartet noch auf Rückgabe
2,3,000000000003,3,2024-02-15,2024-03-15,NaN

---
## 8. Summary — CRUD in Python + SQL

| Operation | What it does | Python method |
|-----------|-------------|---------------|
| **C**reate | Insert new data | `df.to_sql(if_exists='append')` |
| **R**ead | Retrieve data | `pd.read_sql()` |
| **U**pdate | Modify existing data | `engine.connect()` + `text(UPDATE query)` |
| **D**elete | Remove data | `engine.connect()` + `text(DELETE query)` |

These four operations are the foundation of any database-driven application — including Liane's Library! 📚